project:
  type: book
  output-dir: _output
  pre-render: scripts/pre-render.R
  post-render: scripts/post-render.R

book:
  title: "ASML Stock Price Analysis"
  subtitle: "Project of Time Series Analysis for Economic and Financial Data"
  author: "Daniele Tambone"
  date: last-modified
  chapters:
    - index.qmd
    - qmd/01-EDA.qmd
    - qmd/02-return-analysis.qmd
    - qmd/03-volatility-analysis.qmd
  repo-url: https://github.com/DanieleT25/ASML-Stock-Price-Analysis
  repo-actions: [source, issue]

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    number-sections: true
    toc-depth: 3
    smooth-scroll: true
  pdf:
    documentclass: scrreport
    output-file: "ASML-Stock-Price-Analysis"
    toc: true
    number-sections: true
    colorlinks: true
    code-overflow: wrap
    fontsize: 11pt

    geometry:
      - top=30mm
      - left=20mm
      - right=20mm
      - bottom=30mm

    execute:
      out-width: "100%"
      fig-asp: 0.618
      fig-pos: 'H'

    monofont-options: 
      - "Scale=0.8"

execute:
  freeze: auto